package org.mbmg;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class PageSketch extends CustomComponent
{
    
    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_3;
    @AutoGenerated
    private Panel panelContent;
    @AutoGenerated
    private VerticalLayout verticalLayout_7;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private NativeButton ButtonTimeWeek;
    @AutoGenerated
    private NativeButton ButtonTimeMonth;
    @AutoGenerated
    private NativeButton ButtonTimeYear;
    @AutoGenerated
    private Embedded embedded_Graph;
    @AutoGenerated
    private Link linkDownloadXML;
    @AutoGenerated
    private Link linkDownloadCSV;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private Panel panelRTDataNav;
    @AutoGenerated
    private VerticalLayout verticalLayout_5;
    @AutoGenerated
    private Link link_4;
    @AutoGenerated
    private Link link_3;
    @AutoGenerated
    private Link link_2;
    @AutoGenerated
    private Panel PanelPicture;
    @AutoGenerated
    private VerticalLayout verticalLayout_4;
    @AutoGenerated
    private Embedded embedded_2;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_4;
    @AutoGenerated
    private Link LinkHome;
    @AutoGenerated
    private Link LinkAbout;
    @AutoGenerated
    private Link link_1;
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public PageSketch()
    {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        
        // TODO add user code here
    }
    
    @AutoGenerated
    private VerticalLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // horizontalLayout_4
        horizontalLayout_4 = buildHorizontalLayout_4();
        mainLayout.addComponent(horizontalLayout_4);
        mainLayout.setComponentAlignment(horizontalLayout_4, new Alignment(20));
        
        // horizontalLayout_3
        horizontalLayout_3 = buildHorizontalLayout_3();
        mainLayout.addComponent(horizontalLayout_3);
        mainLayout.setExpandRatio(horizontalLayout_3, 1.0f);
        
        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_4()
    {
        // common part: create layout
        horizontalLayout_4 = new HorizontalLayout();
        horizontalLayout_4.setImmediate(false);
        horizontalLayout_4.setWidth("280px");
        horizontalLayout_4.setHeight("-1px");
        horizontalLayout_4.setMargin(false);
        
        // link_1
        link_1 = new Link();
        link_1.setCaption("Link");
        link_1.setImmediate(false);
        link_1.setWidth("-1px");
        link_1.setHeight("-1px");
        horizontalLayout_4.addComponent(link_1);
        
        // LinkAbout
        LinkAbout = new Link();
        LinkAbout.setCaption("About");
        LinkAbout.setImmediate(false);
        LinkAbout.setWidth("-1px");
        LinkAbout.setHeight("-1px");
        horizontalLayout_4.addComponent(LinkAbout);
        
        // LinkHome
        LinkHome = new Link();
        LinkHome.setCaption("Home");
        LinkHome.setImmediate(false);
        LinkHome.setWidth("-1px");
        LinkHome.setHeight("-1px");
        horizontalLayout_4.addComponent(LinkHome);
        
        return horizontalLayout_4;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_3()
    {
        // common part: create layout
        horizontalLayout_3 = new HorizontalLayout();
        horizontalLayout_3.setImmediate(false);
        horizontalLayout_3.setWidth("100.0%");
        horizontalLayout_3.setHeight("100.0%");
        horizontalLayout_3.setMargin(false);
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        horizontalLayout_3.addComponent(verticalLayout_2);
        
        // panelContent
        panelContent = buildPanelContent();
        horizontalLayout_3.addComponent(panelContent);
        horizontalLayout_3.setExpandRatio(panelContent, 1.0f);
        
        return horizontalLayout_3;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2()
    {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("300px");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        
        // PanelPicture
        PanelPicture = buildPanelPicture();
        verticalLayout_2.addComponent(PanelPicture);
        
        // panelRTDataNav
        panelRTDataNav = buildPanelRTDataNav();
        verticalLayout_2.addComponent(panelRTDataNav);
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private Panel buildPanelPicture()
    {
        // common part: create layout
        PanelPicture = new Panel();
        PanelPicture.setCaption("Picture Label");
        PanelPicture.setImmediate(false);
        PanelPicture.setWidth("100.0%");
        PanelPicture.setHeight("-1px");
        
        // verticalLayout_4
        verticalLayout_4 = buildVerticalLayout_4();
        PanelPicture.setContent(verticalLayout_4);
        
        return PanelPicture;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_4()
    {
        // common part: create layout
        verticalLayout_4 = new VerticalLayout();
        verticalLayout_4.setImmediate(false);
        verticalLayout_4.setWidth("-1px");
        verticalLayout_4.setHeight("-1px");
        verticalLayout_4.setMargin(false);
        
        // embedded_2
        embedded_2 = new Embedded();
        embedded_2.setImmediate(false);
        embedded_2.setWidth("-1px");
        embedded_2.setHeight("-1px");
        embedded_2.setSource(new ThemeResource(
                "img/component/embedded_icon.png"));
        embedded_2.setType(1);
        embedded_2.setMimeType("image/png");
        verticalLayout_4.addComponent(embedded_2);
        
        return verticalLayout_4;
    }

    @AutoGenerated
    private Panel buildPanelRTDataNav()
    {
        // common part: create layout
        panelRTDataNav = new Panel();
        panelRTDataNav.setCaption("Real Time Data Navigation");
        panelRTDataNav.setImmediate(false);
        panelRTDataNav.setWidth("100.0%");
        panelRTDataNav.setHeight("73px");
        
        // verticalLayout_5
        verticalLayout_5 = buildVerticalLayout_5();
        panelRTDataNav.setContent(verticalLayout_5);
        
        return panelRTDataNav;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_5()
    {
        // common part: create layout
        verticalLayout_5 = new VerticalLayout();
        verticalLayout_5.setImmediate(false);
        verticalLayout_5.setWidth("-1px");
        verticalLayout_5.setHeight("-1px");
        verticalLayout_5.setMargin(false);
        
        // link_2
        link_2 = new Link();
        link_2.setCaption("Link");
        link_2.setImmediate(false);
        link_2.setWidth("-1px");
        link_2.setHeight("-1px");
        verticalLayout_5.addComponent(link_2);
        
        // link_3
        link_3 = new Link();
        link_3.setCaption("Link");
        link_3.setImmediate(false);
        link_3.setWidth("-1px");
        link_3.setHeight("-1px");
        verticalLayout_5.addComponent(link_3);
        
        // link_4
        link_4 = new Link();
        link_4.setCaption("Link");
        link_4.setImmediate(false);
        link_4.setWidth("-1px");
        link_4.setHeight("-1px");
        verticalLayout_5.addComponent(link_4);
        
        return verticalLayout_5;
    }

    @AutoGenerated
    private Panel buildPanelContent()
    {
        // common part: create layout
        panelContent = new Panel();
        panelContent.setCaption("Content Panel");
        panelContent.setImmediate(false);
        panelContent.setWidth("100.0%");
        panelContent.setHeight("100.0%");
        
        // verticalLayout_7
        verticalLayout_7 = buildVerticalLayout_7();
        panelContent.setContent(verticalLayout_7);
        
        return panelContent;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_7()
    {
        // common part: create layout
        verticalLayout_7 = new VerticalLayout();
        verticalLayout_7.setImmediate(false);
        verticalLayout_7.setWidth("100.0%");
        verticalLayout_7.setHeight("100.0%");
        verticalLayout_7.setMargin(false);
        
        // linkDownloadCSV
        linkDownloadCSV = new Link();
        linkDownloadCSV.setCaption("Download CSV Data");
        linkDownloadCSV.setImmediate(false);
        linkDownloadCSV.setWidth("-1px");
        linkDownloadCSV.setHeight("-1px");
        verticalLayout_7.addComponent(linkDownloadCSV);
        
        // linkDownloadXML
        linkDownloadXML = new Link();
        linkDownloadXML.setCaption("Download XML Data");
        linkDownloadXML.setImmediate(false);
        linkDownloadXML.setWidth("-1px");
        linkDownloadXML.setHeight("-1px");
        verticalLayout_7.addComponent(linkDownloadXML);
        
        // embedded_Graph
        embedded_Graph = new Embedded();
        embedded_Graph.setImmediate(false);
        embedded_Graph.setWidth("100.0%");
        embedded_Graph.setHeight("100.0%");
        embedded_Graph.setSource(new ThemeResource(
                "img/component/embedded_icon.png"));
        embedded_Graph.setType(1);
        embedded_Graph.setMimeType("image/png");
        verticalLayout_7.addComponent(embedded_Graph);
        verticalLayout_7.setExpandRatio(embedded_Graph, 1.0f);
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_7.addComponent(horizontalLayout_1);
        
        return verticalLayout_7;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1()
    {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);
        
        // ButtonTimeYear
        ButtonTimeYear = new NativeButton();
        ButtonTimeYear.setCaption("Year");
        ButtonTimeYear.setImmediate(false);
        ButtonTimeYear.setWidth("-1px");
        ButtonTimeYear.setHeight("-1px");
        horizontalLayout_1.addComponent(ButtonTimeYear);
        
        // ButtonTimeMonth
        ButtonTimeMonth = new NativeButton();
        ButtonTimeMonth.setCaption("Month");
        ButtonTimeMonth.setImmediate(false);
        ButtonTimeMonth.setWidth("-1px");
        ButtonTimeMonth.setHeight("-1px");
        horizontalLayout_1.addComponent(ButtonTimeMonth);
        
        // ButtonTimeWeek
        ButtonTimeWeek = new NativeButton();
        ButtonTimeWeek.setCaption("Week");
        ButtonTimeWeek.setImmediate(false);
        ButtonTimeWeek.setWidth("-1px");
        ButtonTimeWeek.setHeight("-1px");
        horizontalLayout_1.addComponent(ButtonTimeWeek);
        
        return horizontalLayout_1;
    }
    
}
